server:
  port: 8086

spring:
  application:
    name: ms-file-upload

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Geliştirme aşamasında tabloyu otomatik günceller
    show-sql: true      # Konsolda SQL log görebilmek için

  rabbitmq:
    host: localhost
    port: 5672  # BURAYI DÜZENLEDİM
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka/  # Eureka Server URL
      register-with-eureka: true  # Eureka serverinə qeydiyyat
      fetch-registry: true  # Eureka serverdən qeydiyyat al
      instance-info-replication-interval-seconds: 10  # Yenilənmə intervalı

logging:
  level:
    root: INFO
    # Uygulamamızın kendi paketlerinde detaylı log isterseniz:
    az.xalqbank.msphotostorage: DEBUG
