server:
  port: 8086

spring:
  application:
    name: ms-file-upload
  datasource:
    url: jdbc:postgresql://postgres-file-upload:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis
      port: 6379
  eureka:
    client:
      service-url:
        default-zone: http://eureka-server:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
      instance-info-replication-interval-seconds: 10

logging:
  level:
    root: INFO
    az.xalqbank.msphotostorage: DEBUG
