server:
  port: 8083

spring:
  application:
    name: ms-photo-storage

  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  amqp:
    deserialization:
      trust:
        all: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  data:
    redis:
      host: localhost
      port: 6381

logging:
  level:
    root: INFO
    az.xalqbank.msphotostorage: DEBUG