spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: ms-customer
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers/**
