server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-customer
          uri: http://ms-customers:8085/
          predicates:
            - Path=/api/v1/customers/**
        - id: ms-file-upload
          uri: http://ms-file-upload:8086/
          predicates:
            - Path=/api/v1/files/**
        - id: ms-transaction
          uri: http://ms-transaction-events:8083/
          predicates:
            - Path=/api/v1/transactions/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
application:
  cors:
    allowedOrigins: "*"
    allowedHeaders: "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
