server:
  port: 8085
spring:
  application:
    name: ms-customers

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: HikariCP
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true  # Eureka serverinə qeydiyyat
      fetch-registry: true  # Eureka serverdən qeydiyyat al
      instance-info-replication-interval-seconds: 10  # Yenilənmə intervalı